Create multiprocess-draft.py
Should work but haven't tested it because of this error message:

Traceback (most recent call last):
  File "program.py", line 256, in <module>
    print(connect_four(board, player))
  File "program.py", line 243, in connect_four
    depth_search(contents, turn, max_depth)
  File "program.py", line 218, in depth_search
    with Pool(processes=6) as pool:
  File "/opt/python-3.6/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/opt/python-3.6/lib/python3.6/multiprocessing/pool.py", line 174, in __init__
    self._repopulate_pool()
  File "/opt/python-3.6/lib/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/opt/python-3.6/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/opt/python-3.6/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/opt/python-3.6/lib/python3.6/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/opt/python-3.6/lib/python3.6/multiprocessing/popen_fork.py", line 67, in _launch
    self.pid = os.fork()
BlockingIOError: [Errno 11] Resource temporarily unavailable

I don't know if this is something about the system I'm using or if the test is actively blocking us from using multiprocessing. I put the question on Ed.
The other concurrent option here is to split the pool among different max-depth searches: start the deep & shallow searches at the same time, write all their results to a global variable, and only allow the lock to be handed to threads doing deeper searches, so they can get more lead time and we'll still have a result if they don't finish. Implementing that wouldn't take long